//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFGT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public Nullable<bool> Opiniao { get; set; }
        public int UserID { get; set; }
        public int EventosID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Evento Evento { get; set; }
    }
}
