//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFGT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizadore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organizadore()
        {
            this.Eventos = new HashSet<Evento>();
        }
    
        public int OrgID { get; set; }
        public string NomeOrg { get; set; }
        public string Email {get; set; }
        public string Nipc { get; set; }
        public string Password { get; set; }
        public string LinkFotoORG { get; set; }    // A photo vai para aqui, tlvz vou ter que mudar para public byte[] UserPhoto { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Eventos { get; set; }
    }
}
